"""Default entity configuration for CANDYSIGN CoCan (小电拼) Pro.

This config is used as a pre-filled template when a user first sets up
the integration. They can then modify, add, or remove entities through
the HA UI without touching code.

Each entity config is a plain dict. See README for field documentation.

Field paths verified against real MCP server response structure (2025-01).
"""

from __future__ import annotations

# Default entity configuration for CoCan Pro (5-port charger)
# All field paths verified against actual MCP server API responses.
DEFAULT_ENTITIES_CONFIG: list[dict] = [
    # ── Total Power (sum of all ports vout * iout) ────────────
    {
        "name": "Total Power",
        "unique_id": "total_power",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "compute": "sum_multiply",
        "field_sources": [
            {"field_a": "ports.0.vout_mv", "field_b": "ports.0.iout_ma"},
            {"field_a": "ports.1.vout_mv", "field_b": "ports.1.iout_ma"},
            {"field_a": "ports.2.vout_mv", "field_b": "ports.2.iout_ma"},
            {"field_a": "ports.3.vout_mv", "field_b": "ports.3.iout_ma"},
            {"field_a": "ports.4.vout_mv", "field_b": "ports.4.iout_ma"},
        ],
        "divide_by": 1000000,
        "round_digits": 2,
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
    },
    # ── Per-port sensors (Port A = port 1) ─────────────────────
    {
        "name": "Port A Power",
        "unique_id": "port_1_power",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "compute": "multiply",
        "field_a": "ports.0.vout_mv",
        "field_b": "ports.0.iout_ma",
        "divide_by": 1000000,
        "round_digits": 2,
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
    },
    {
        "name": "Port A Voltage",
        "unique_id": "port_1_voltage",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.0.vout_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
    },
    {
        "name": "Port A Current",
        "unique_id": "port_1_current",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.0.iout_ma",
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "divide_by": 1000,
        "round_digits": 3,
        "icon": "mdi:current-ac",
    },
    {
        "name": "Port A Temperature",
        "unique_id": "port_1_temp",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.0.die_temperature",
        "icon": "mdi:thermometer",
    },
    {
        "name": "Port A Connected",
        "unique_id": "port_1_connected",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.0.connected",
        "icon": "mdi:cellphone-link",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port A Fast Charge Protocol",
        "unique_id": "port_1_protocol",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.0.fc_protocol",
        "icon": "mdi:lightning-bolt-circle",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port A Session Charge",
        "unique_id": "port_1_session_mwh",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.0.session_charge_mwh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "unit": "mWh",
        "icon": "mdi:counter",
        "entity_category": "diagnostic",
    },
    # ── Port C1 (port 2) ───────────────────────────────────────
    {
        "name": "Port C1 Power",
        "unique_id": "port_2_power",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "compute": "multiply",
        "field_a": "ports.1.vout_mv",
        "field_b": "ports.1.iout_ma",
        "divide_by": 1000000,
        "round_digits": 2,
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
    },
    {
        "name": "Port C1 Voltage",
        "unique_id": "port_2_voltage",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.1.vout_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
    },
    {
        "name": "Port C1 Current",
        "unique_id": "port_2_current",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.1.iout_ma",
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "divide_by": 1000,
        "round_digits": 3,
        "icon": "mdi:current-ac",
    },
    {
        "name": "Port C1 Temperature",
        "unique_id": "port_2_temp",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.1.die_temperature",
        "icon": "mdi:thermometer",
    },
    {
        "name": "Port C1 Connected",
        "unique_id": "port_2_connected",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.1.connected",
        "icon": "mdi:cellphone-link",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Fast Charge Protocol",
        "unique_id": "port_2_protocol",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.1.fc_protocol",
        "icon": "mdi:lightning-bolt-circle",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Session Charge",
        "unique_id": "port_2_session_mwh",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.1.session_charge_mwh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "unit": "mWh",
        "icon": "mdi:counter",
        "entity_category": "diagnostic",
    },
    # ── Port C2 (port 3) ───────────────────────────────────────
    {
        "name": "Port C2 Power",
        "unique_id": "port_3_power",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "compute": "multiply",
        "field_a": "ports.2.vout_mv",
        "field_b": "ports.2.iout_ma",
        "divide_by": 1000000,
        "round_digits": 2,
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
    },
    {
        "name": "Port C2 Voltage",
        "unique_id": "port_3_voltage",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.2.vout_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
    },
    {
        "name": "Port C2 Current",
        "unique_id": "port_3_current",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.2.iout_ma",
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "divide_by": 1000,
        "round_digits": 3,
        "icon": "mdi:current-ac",
    },
    {
        "name": "Port C2 Temperature",
        "unique_id": "port_3_temp",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.2.die_temperature",
        "icon": "mdi:thermometer",
    },
    {
        "name": "Port C2 Connected",
        "unique_id": "port_3_connected",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.2.connected",
        "icon": "mdi:cellphone-link",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Fast Charge Protocol",
        "unique_id": "port_3_protocol",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.2.fc_protocol",
        "icon": "mdi:lightning-bolt-circle",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Session Charge",
        "unique_id": "port_3_session_mwh",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.2.session_charge_mwh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "unit": "mWh",
        "icon": "mdi:counter",
        "entity_category": "diagnostic",
    },
    # ── Port C3 (port 4) ───────────────────────────────────────
    {
        "name": "Port C3 Power",
        "unique_id": "port_4_power",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "compute": "multiply",
        "field_a": "ports.3.vout_mv",
        "field_b": "ports.3.iout_ma",
        "divide_by": 1000000,
        "round_digits": 2,
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
    },
    {
        "name": "Port C3 Voltage",
        "unique_id": "port_4_voltage",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.3.vout_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
    },
    {
        "name": "Port C3 Current",
        "unique_id": "port_4_current",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.3.iout_ma",
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "divide_by": 1000,
        "round_digits": 3,
        "icon": "mdi:current-ac",
    },
    {
        "name": "Port C3 Temperature",
        "unique_id": "port_4_temp",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.3.die_temperature",
        "icon": "mdi:thermometer",
    },
    {
        "name": "Port C3 Connected",
        "unique_id": "port_4_connected",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.3.connected",
        "icon": "mdi:cellphone-link",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Fast Charge Protocol",
        "unique_id": "port_4_protocol",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.3.fc_protocol",
        "icon": "mdi:lightning-bolt-circle",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Session Charge",
        "unique_id": "port_4_session_mwh",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.3.session_charge_mwh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "unit": "mWh",
        "icon": "mdi:counter",
        "entity_category": "diagnostic",
    },
    # ── Port C4 (port 5) ───────────────────────────────────────
    {
        "name": "Port C4 Power",
        "unique_id": "port_5_power",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "compute": "multiply",
        "field_a": "ports.4.vout_mv",
        "field_b": "ports.4.iout_ma",
        "divide_by": 1000000,
        "round_digits": 2,
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
    },
    {
        "name": "Port C4 Voltage",
        "unique_id": "port_5_voltage",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.4.vout_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
    },
    {
        "name": "Port C4 Current",
        "unique_id": "port_5_current",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.4.iout_ma",
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "divide_by": 1000,
        "round_digits": 3,
        "icon": "mdi:current-ac",
    },
    {
        "name": "Port C4 Temperature",
        "unique_id": "port_5_temp",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.4.die_temperature",
        "icon": "mdi:thermometer",
    },
    {
        "name": "Port C4 Connected",
        "unique_id": "port_5_connected",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.4.connected",
        "icon": "mdi:cellphone-link",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Fast Charge Protocol",
        "unique_id": "port_5_protocol",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.4.fc_protocol",
        "icon": "mdi:lightning-bolt-circle",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Session Charge",
        "unique_id": "port_5_session_mwh",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.4.session_charge_mwh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "unit": "mWh",
        "icon": "mdi:counter",
        "entity_category": "diagnostic",
    },
    # ── Per-port input voltage (vin_mv) ────────────────────────
    {
        "name": "Port A Input Voltage",
        "unique_id": "port_1_vin",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.0.vin_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Input Voltage",
        "unique_id": "port_2_vin",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.1.vin_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Input Voltage",
        "unique_id": "port_3_vin",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.2.vin_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Input Voltage",
        "unique_id": "port_4_vin",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.3.vin_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Input Voltage",
        "unique_id": "port_5_vin",
        "type": "sensor",
        "poll_tool": "get_port_details",
        "field": "ports.4.vin_mv",
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "divide_by": 1000,
        "round_digits": 2,
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    # ── Charging status switches (bitmask-based) ───────────────
    {
        "name": "Port A Charging",
        "unique_id": "port_1_charging",
        "type": "switch",
        "on_tool": "turn_on_port",
        "on_args": {"ports": [1]},
        "off_tool": "turn_off_port",
        "off_args": {"ports": [1]},
        "poll_tool": "get_charging_status",
        "field": "status_bitmask",
        "field_is_bitmask": True,
        "bitmask_bit": 0,
        "icon": "mdi:power-plug",
    },
    {
        "name": "Port C1 Charging",
        "unique_id": "port_2_charging",
        "type": "switch",
        "on_tool": "turn_on_port",
        "on_args": {"ports": [2]},
        "off_tool": "turn_off_port",
        "off_args": {"ports": [2]},
        "poll_tool": "get_charging_status",
        "field": "status_bitmask",
        "field_is_bitmask": True,
        "bitmask_bit": 1,
        "icon": "mdi:power-plug",
    },
    {
        "name": "Port C2 Charging",
        "unique_id": "port_3_charging",
        "type": "switch",
        "on_tool": "turn_on_port",
        "on_args": {"ports": [3]},
        "off_tool": "turn_off_port",
        "off_args": {"ports": [3]},
        "poll_tool": "get_charging_status",
        "field": "status_bitmask",
        "field_is_bitmask": True,
        "bitmask_bit": 2,
        "icon": "mdi:power-plug",
    },
    {
        "name": "Port C3 Charging",
        "unique_id": "port_4_charging",
        "type": "switch",
        "on_tool": "turn_on_port",
        "on_args": {"ports": [4]},
        "off_tool": "turn_off_port",
        "off_args": {"ports": [4]},
        "poll_tool": "get_charging_status",
        "field": "status_bitmask",
        "field_is_bitmask": True,
        "bitmask_bit": 3,
        "icon": "mdi:power-plug",
    },
    {
        "name": "Port C4 Charging",
        "unique_id": "port_5_charging",
        "type": "switch",
        "on_tool": "turn_on_port",
        "on_args": {"ports": [5]},
        "off_tool": "turn_off_port",
        "off_args": {"ports": [5]},
        "poll_tool": "get_charging_status",
        "field": "status_bitmask",
        "field_is_bitmask": True,
        "bitmask_bit": 4,
        "icon": "mdi:power-plug",
    },
    # ── Charging strategy (select) ─────────────────────────────
    {
        "name": "Charging Strategy",
        "unique_id": "charging_strategy",
        "type": "select",
        "set_tool": "set_charging_strategy",
        "set_arg_name": "strategy",
        "options": [0, 1, 6, 7, 8],
        "option_labels": [
            "FAST / 自由流",
            "SLOW / 均衡",
            "USBA Charging / 小家电",
            "HIGH PERFORMANCE / 高性能",
            "ULTRA FAST SINGLE PORT / 单口极速",
        ],
        "field": "__coordinator__.charging_strategy",
        "icon": "mdi:cogs",
    },
    # ── Temperature mode (select) ────────────────────────────────
    {
        "name": "Temperature Mode",
        "unique_id": "temperature_mode",
        "type": "select",
        "set_tool": "set_temperature_mode",
        "set_arg_name": "mode",
        "options": [0, 1],
        "option_labels": [
            "POWER_PRIORITY / 性能优先",
            "TEMPERATURE_PRIORITY / 温控优先",
        ],
        "poll_tool": "get_temperature_mode",
        "field": "mode",
        "value_map": {"0": "POWER_PRIORITY", "1": "TEMPERATURE_PRIORITY"},
        "icon": "mdi:thermometer-chevron-up",
    },
    # ── Display brightness (select) ────────────────────────────
    {
        "name": "Display Brightness",
        "unique_id": "display_brightness",
        "type": "select",
        "set_tool": "set_display_intensity",
        "set_arg_name": "level",
        "options": ["关", "低", "中", "高"],
        "option_labels": ["Off", "Low", "Medium", "High"],
        "poll_tool": "get_display_config",
        "field": "level",
        "icon": "mdi:brightness-6",
    },
    # ── CP02S Display options (selects) ───────────────────────
    {
        "name": "Display Mode",
        "unique_id": "display_mode",
        "type": "select",
        "set_tool": "set_status_display_mode",
        "set_arg_name": "mode",
        "options": ["待机动画优先", "功率显示优先"],
        "option_labels": ["Animation Priority", "Power Display Priority"],
        "poll_tool": "get_display_config",
        "field": "display_mode",
        "icon": "mdi:monitor",
    },
    {
        "name": "Idle Display",
        "unique_id": "idle_display",
        "type": "select",
        "set_tool": "set_idle_display",
        "set_arg_name": "idle_display",
        "options": ["流星", "落花", "康威的生命游戏", "时间"],
        "option_labels": ["Meteor", "Falling Petals", "Conway's Game of Life", "Clock"],
        "poll_tool": "get_display_config",
        "field": "idle_display",
        "icon": "mdi:image",
    },
    # ── CP02S Hourly chime (switch) ───────────────────────────
    {
        "name": "Hourly Chime",
        "unique_id": "hourly_chime",
        "type": "switch",
        "on_tool": "set_hourly_chime",
        "on_args": {"enabled": True},
        "off_tool": "set_hourly_chime",
        "off_args": {"enabled": False},
        "poll_tool": "get_display_config",
        "field": "hourly_chime",
        "icon": "mdi:bell-outline",
    },
    # ── Machine facts (device-level) ──────────────────────────
    {
        "name": "Product Model",
        "unique_id": "product_family",
        "type": "sensor",
        "poll_tool": "get_machine_facts",
        "field": "product_family",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    {
        "name": "Max Power Budget",
        "unique_id": "max_power_budget",
        "type": "sensor",
        "poll_tool": "get_machine_facts",
        "field": "max_power_budget",
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
        "entity_category": "diagnostic",
    },
    # ── Device info (device-level) ─────────────────────────────
    {
        "name": "Device PSN",
        "unique_id": "device_psn",
        "type": "sensor",
        "poll_tool": "get_device_info",
        "field": "psn",
        "icon": "mdi:barcode",
        "entity_category": "diagnostic",
    },
    {
        "name": "Firmware Version",
        "unique_id": "firmware_version",
        "type": "sensor",
        "poll_tool": "get_device_info",
        "field": "fpga_version",
        "icon": "mdi:update",
        "entity_category": "diagnostic",
    },
    {
        "name": "WiFi SSID",
        "unique_id": "wifi_ssid",
        "type": "sensor",
        "poll_tool": "get_device_info",
        "field": "ssid",
        "icon": "mdi:wifi",
        "entity_category": "diagnostic",
    },
    {
        "name": "WiFi BSSID",
        "unique_id": "wifi_bssid",
        "type": "sensor",
        "poll_tool": "get_device_info",
        "field": "bssid",
        "icon": "mdi:router-wireless",
        "entity_category": "diagnostic",
    },
    {
        "name": "WiFi Channel",
        "unique_id": "wifi_channel",
        "type": "sensor",
        "poll_tool": "get_device_info",
        "field": "channel",
        "icon": "mdi:wifi-strength-4",
        "entity_category": "diagnostic",
    },
    {
        "name": "WiFi Protocol",
        "unique_id": "wifi_protocol",
        "type": "sensor",
        "poll_tool": "get_device_info",
        "field": "wifi_protocol",
        "icon": "mdi:wifi",
        "entity_category": "diagnostic",
    },
    {
        "name": "WiFi Signal",
        "unique_id": "wifi_rssi",
        "type": "sensor",
        "poll_tool": "get_device_info",
        "field": "rssi",
        "device_class": "signal_strength",
        "state_class": "measurement",
        "unit": "dBm",
        "icon": "mdi:signal",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Connected device name ──────────────────────
    {
        "name": "Port A Connected Device",
        "unique_id": "port_1_pd_device",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].device_name_zh",
        "icon": "mdi:cellphone",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Connected Device",
        "unique_id": "port_2_pd_device",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].device_name_zh",
        "icon": "mdi:cellphone",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Connected Device",
        "unique_id": "port_3_pd_device",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].device_name_zh",
        "icon": "mdi:cellphone",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Connected Device",
        "unique_id": "port_4_pd_device",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].device_name_zh",
        "icon": "mdi:cellphone",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Connected Device",
        "unique_id": "port_5_pd_device",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].device_name_zh",
        "icon": "mdi:cellphone",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Device brand ───────────────────────────────
    {
        "name": "Port A Device Brand",
        "unique_id": "port_1_pd_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].device_brand_zh",
        "icon": "mdi:label-variant",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Device Brand",
        "unique_id": "port_2_pd_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].device_brand_zh",
        "icon": "mdi:label-variant",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Device Brand",
        "unique_id": "port_3_pd_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].device_brand_zh",
        "icon": "mdi:label-variant",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Device Brand",
        "unique_id": "port_4_pd_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].device_brand_zh",
        "icon": "mdi:label-variant",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Device Brand",
        "unique_id": "port_5_pd_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].device_brand_zh",
        "icon": "mdi:label-variant",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Cable name ──────────────────────────────────
    {
        "name": "Port A Cable",
        "unique_id": "port_1_pd_cable",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].cable_name_zh",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Cable",
        "unique_id": "port_2_pd_cable",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].cable_name_zh",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Cable",
        "unique_id": "port_3_pd_cable",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].cable_name_zh",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Cable",
        "unique_id": "port_4_pd_cable",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].cable_name_zh",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Cable",
        "unique_id": "port_5_pd_cable",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].cable_name_zh",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Cable brand ────────────────────────────────
    {
        "name": "Port A Cable Brand",
        "unique_id": "port_1_pd_cable_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].cable_brand_zh",
        "icon": "mdi:tag-multiple",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Cable Brand",
        "unique_id": "port_2_pd_cable_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].cable_brand_zh",
        "icon": "mdi:tag-multiple",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Cable Brand",
        "unique_id": "port_3_pd_cable_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].cable_brand_zh",
        "icon": "mdi:tag-multiple",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Cable Brand",
        "unique_id": "port_4_pd_cable_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].cable_brand_zh",
        "icon": "mdi:tag-multiple",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Cable Brand",
        "unique_id": "port_5_pd_cable_brand",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].cable_brand_zh",
        "icon": "mdi:tag-multiple",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Cable max voltage ──────────────────────────
    {
        "name": "Port A Cable Max Voltage",
        "unique_id": "port_1_pd_cable_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].cable_max_vbus_voltage",
        "icon": "mdi:flash-outline",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Cable Max Voltage",
        "unique_id": "port_2_pd_cable_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].cable_max_vbus_voltage",
        "icon": "mdi:flash-outline",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Cable Max Voltage",
        "unique_id": "port_3_pd_cable_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].cable_max_vbus_voltage",
        "icon": "mdi:flash-outline",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Cable Max Voltage",
        "unique_id": "port_4_pd_cable_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].cable_max_vbus_voltage",
        "icon": "mdi:flash-outline",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Cable Max Voltage",
        "unique_id": "port_5_pd_cable_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].cable_max_vbus_voltage",
        "icon": "mdi:flash-outline",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Has E-Marker ────────────────────────────────
    {
        "name": "Port A E-Marker",
        "unique_id": "port_1_pd_emarker",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].has_emarker",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 E-Marker",
        "unique_id": "port_2_pd_emarker",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].has_emarker",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 E-Marker",
        "unique_id": "port_3_pd_emarker",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].has_emarker",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 E-Marker",
        "unique_id": "port_4_pd_emarker",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].has_emarker",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 E-Marker",
        "unique_id": "port_5_pd_emarker",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].has_emarker",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    # ── PD Status: PD revision ────────────────────────────────
    {
        "name": "Port A PD Revision",
        "unique_id": "port_1_pd_rev",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].pd_revision",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 PD Revision",
        "unique_id": "port_2_pd_rev",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].pd_revision",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 PD Revision",
        "unique_id": "port_3_pd_rev",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].pd_revision",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 PD Revision",
        "unique_id": "port_4_pd_rev",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].pd_revision",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 PD Revision",
        "unique_id": "port_5_pd_rev",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].pd_revision",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Operating voltage ──────────────────────────
    {
        "name": "Port A Operating Voltage",
        "unique_id": "port_1_pd_op_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].operating_voltage",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Operating Voltage",
        "unique_id": "port_2_pd_op_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].operating_voltage",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Operating Voltage",
        "unique_id": "port_3_pd_op_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].operating_voltage",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Operating Voltage",
        "unique_id": "port_4_pd_op_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].operating_voltage",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Operating Voltage",
        "unique_id": "port_5_pd_op_v",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].operating_voltage",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "voltage",
        "state_class": "measurement",
        "unit": "V",
        "icon": "mdi:sine-wave",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Operating current ──────────────────────────
    {
        "name": "Port A Operating Current",
        "unique_id": "port_1_pd_op_a",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].operating_current",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "icon": "mdi:current-ac",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Operating Current",
        "unique_id": "port_2_pd_op_a",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].operating_current",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "icon": "mdi:current-ac",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Operating Current",
        "unique_id": "port_3_pd_op_a",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].operating_current",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "icon": "mdi:current-ac",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Operating Current",
        "unique_id": "port_4_pd_op_a",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].operating_current",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "icon": "mdi:current-ac",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Operating Current",
        "unique_id": "port_5_pd_op_a",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].operating_current",
        "divide_by": 1000,
        "round_digits": 1,
        "device_class": "current",
        "state_class": "measurement",
        "unit": "A",
        "icon": "mdi:current-ac",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Status temperature ──────────────────────────
    {
        "name": "Port A PD Status Temperature",
        "unique_id": "port_1_pd_temp",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].status_temperature",
        "device_class": "temperature",
        "state_class": "measurement",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 PD Status Temperature",
        "unique_id": "port_2_pd_temp",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].status_temperature",
        "device_class": "temperature",
        "state_class": "measurement",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 PD Status Temperature",
        "unique_id": "port_3_pd_temp",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].status_temperature",
        "device_class": "temperature",
        "state_class": "measurement",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 PD Status Temperature",
        "unique_id": "port_4_pd_temp",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].status_temperature",
        "device_class": "temperature",
        "state_class": "measurement",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 PD Status Temperature",
        "unique_id": "port_5_pd_temp",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].status_temperature",
        "device_class": "temperature",
        "state_class": "measurement",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Request PDO ID ─────────────────────────────
    {
        "name": "Port A Request PDO",
        "unique_id": "port_1_pd_pdo",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].request_pdo_id",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Request PDO",
        "unique_id": "port_2_pd_pdo",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].request_pdo_id",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Request PDO",
        "unique_id": "port_3_pd_pdo",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].request_pdo_id",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Request PDO",
        "unique_id": "port_4_pd_pdo",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].request_pdo_id",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Request PDO",
        "unique_id": "port_5_pd_pdo",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].request_pdo_id",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Cable is active ──────────────────────────
    {
        "name": "Port A Active Cable",
        "unique_id": "port_1_pd_cable_active",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].cable_is_active",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Active Cable",
        "unique_id": "port_2_pd_cable_active",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].cable_is_active",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Active Cable",
        "unique_id": "port_3_pd_cable_active",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].cable_is_active",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Active Cable",
        "unique_id": "port_4_pd_cable_active",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].cable_is_active",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Active Cable",
        "unique_id": "port_5_pd_cable_active",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].cable_is_active",
        "icon": "mdi:cable-data",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Cable highest speed ────────────────────────
    {
        "name": "Port A Cable USB Speed",
        "unique_id": "port_1_pd_usb_speed",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].cable_usb_highest_speed",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Cable USB Speed",
        "unique_id": "port_2_pd_usb_speed",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].cable_usb_highest_speed",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Cable USB Speed",
        "unique_id": "port_3_pd_usb_speed",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].cable_usb_highest_speed",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Cable USB Speed",
        "unique_id": "port_4_pd_usb_speed",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].cable_usb_highest_speed",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Cable USB Speed",
        "unique_id": "port_5_pd_usb_speed",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].cable_usb_highest_speed",
        "icon": "mdi:usb",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Dual role power ────────────────────────────
    {
        "name": "Port A Dual Role Power",
        "unique_id": "port_1_pd_dual_role",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].dual_role_power",
        "icon": "mdi:sync",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Dual Role Power",
        "unique_id": "port_2_pd_dual_role",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].dual_role_power",
        "icon": "mdi:sync",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Dual Role Power",
        "unique_id": "port_3_pd_dual_role",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].dual_role_power",
        "icon": "mdi:sync",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Dual Role Power",
        "unique_id": "port_4_pd_dual_role",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].dual_role_power",
        "icon": "mdi:sync",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Dual Role Power",
        "unique_id": "port_5_pd_dual_role",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].dual_role_power",
        "icon": "mdi:sync",
        "entity_category": "diagnostic",
    },
    # ── Power allocation (number sliders, shared state) ─────────
    {
        "name": "Port A Power Allocation",
        "unique_id": "port_1_power_alloc",
        "type": "number",
        "set_tool": "set_port_power_allocation",
        "port_index": 1,
        "min": 0,
        "max": 60,
        "step": 1,
        "unit": "W",
        "icon": "mdi:gauge",
    },
    {
        "name": "Port C1 Power Allocation",
        "unique_id": "port_2_power_alloc",
        "type": "number",
        "set_tool": "set_port_power_allocation",
        "port_index": 2,
        "min": 0,
        "max": 140,
        "step": 1,
        "unit": "W",
        "icon": "mdi:gauge",
    },
    {
        "name": "Port C2 Power Allocation",
        "unique_id": "port_3_power_alloc",
        "type": "number",
        "set_tool": "set_port_power_allocation",
        "port_index": 3,
        "min": 0,
        "max": 140,
        "step": 1,
        "unit": "W",
        "icon": "mdi:gauge",
    },
    {
        "name": "Port C3 Power Allocation",
        "unique_id": "port_4_power_alloc",
        "type": "number",
        "set_tool": "set_port_power_allocation",
        "port_index": 4,
        "min": 0,
        "max": 140,
        "step": 1,
        "unit": "W",
        "icon": "mdi:gauge",
    },
    {
        "name": "Port C4 Power Allocation",
        "unique_id": "port_5_power_alloc",
        "type": "number",
        "set_tool": "set_port_power_allocation",
        "port_index": 5,
        "min": 0,
        "max": 140,
        "step": 1,
        "unit": "W",
        "icon": "mdi:gauge",
    },
    # ── Total allocated power (read-only sensor from coordinator) ────
    {
        "name": "Total Allocated Power",
        "unique_id": "total_allocated_power",
        "type": "sensor",
        "poll_tool": "get_machine_facts",
        "field": "__coordinator__.total_allocated_power",
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:gauge-full",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Negotiated power (sink_operational_pdp) ────
    {
        "name": "Port A PD Power",
        "unique_id": "port_1_pd_power",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].sink_operational_pdp",
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 PD Power",
        "unique_id": "port_2_pd_power",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].sink_operational_pdp",
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 PD Power",
        "unique_id": "port_3_pd_power",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].sink_operational_pdp",
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 PD Power",
        "unique_id": "port_4_pd_power",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].sink_operational_pdp",
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 PD Power",
        "unique_id": "port_5_pd_power",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].sink_operational_pdp",
        "device_class": "power",
        "state_class": "measurement",
        "unit": "W",
        "icon": "mdi:flash",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Battery percentage (capacity / design_capacity) ──
    {
        "name": "Port A Battery Level",
        "unique_id": "port_1_pd_battery_pct",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "compute": "divide",
        "field_a": "ports[port=1].battery_present_capacity",
        "field_b": "ports[port=1].battery_design_capacity",
        "multiply_by": 100,
        "round_digits": 0,
        "device_class": "battery",
        "state_class": "measurement",
        "unit": "%",
        "icon": "mdi:battery-50",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Battery Level",
        "unique_id": "port_2_pd_battery_pct",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "compute": "divide",
        "field_a": "ports[port=2].battery_present_capacity",
        "field_b": "ports[port=2].battery_design_capacity",
        "multiply_by": 100,
        "round_digits": 0,
        "device_class": "battery",
        "state_class": "measurement",
        "unit": "%",
        "icon": "mdi:battery-50",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Battery Level",
        "unique_id": "port_3_pd_battery_pct",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "compute": "divide",
        "field_a": "ports[port=3].battery_present_capacity",
        "field_b": "ports[port=3].battery_design_capacity",
        "multiply_by": 100,
        "round_digits": 0,
        "device_class": "battery",
        "state_class": "measurement",
        "unit": "%",
        "icon": "mdi:battery-50",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Battery Level",
        "unique_id": "port_4_pd_battery_pct",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "compute": "divide",
        "field_a": "ports[port=4].battery_present_capacity",
        "field_b": "ports[port=4].battery_design_capacity",
        "multiply_by": 100,
        "round_digits": 0,
        "device_class": "battery",
        "state_class": "measurement",
        "unit": "%",
        "icon": "mdi:battery-50",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Battery Level",
        "unique_id": "port_5_pd_battery_pct",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "compute": "divide",
        "field_a": "ports[port=5].battery_present_capacity",
        "field_b": "ports[port=5].battery_design_capacity",
        "multiply_by": 100,
        "round_digits": 0,
        "device_class": "battery",
        "state_class": "measurement",
        "unit": "%",
        "icon": "mdi:battery-50",
        "entity_category": "diagnostic",
    },
    # ── PD Status: Has battery ────────────────────────────────
    {
        "name": "Port A Battery Present",
        "unique_id": "port_1_pd_battery",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=1].has_battery",
        "icon": "mdi:battery",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C1 Battery Present",
        "unique_id": "port_2_pd_battery",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=2].has_battery",
        "icon": "mdi:battery",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C2 Battery Present",
        "unique_id": "port_3_pd_battery",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=3].has_battery",
        "icon": "mdi:battery",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C3 Battery Present",
        "unique_id": "port_4_pd_battery",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=4].has_battery",
        "icon": "mdi:battery",
        "entity_category": "diagnostic",
    },
    {
        "name": "Port C4 Battery Present",
        "unique_id": "port_5_pd_battery",
        "type": "sensor",
        "poll_tool": "get_port_pd_status",
        "field": "ports[port=5].has_battery",
        "icon": "mdi:battery",
        "entity_category": "diagnostic",
    },
]
